server:
  port: 8800
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # Log
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sv_auth?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
  jackson:
    date-format: HH:mm:ss dd-MM-yyyy
    time-zone: UTC
  redis:
    host: 192.168.56.10
    port: 6379
    database: 0
    timeout: 1800000
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲